# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48430a0770dda465f00c234993055da4ff1c2c463ac90e4fe961d88cebf41a6416842bc4510d7330676b658cba0ca45d09f3d62fa60e5213b987fa6d28cef90

test:
  secret_key_base: 5d68f2192adc22fe66343e7e83f2618e2e166b808b0dd8a63cada6452d4988ce5d3b16e2cd34d1163c3bba3180f81a889fcd2cf6b8c9b06322696c25931803b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
